name: Release
on:
  push:
    tags: ['v*']
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pack artifacts
        run: |
          tar -czf termux-pro-scripts.tgz scripts boot Makefile .editorconfig
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: termux-pro-scripts.tgz
